# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

# The Default Profile
[default]
# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
solc_version = '0.8.15'
auto_detect_solc = false
# EVM setting
evm_version = 'london'
# Increase optimizer_runs
optimizer = true
optimizer_runs = 1_000
via_ir = false
# Fuzz more than the default 256
fuzz_runs = 1_000
# Configure remappings
remappings = [
  '@ds=lib/ds-test/src/',
  '@std=lib/forge-std/src/',
  '@solbase=lib/solbase/src/'
]

# Extreme Fuzzing CI Profile :P
[ci]
fuzz_runs = 100_000
