[profile.default]
solc = "0.8.17"
bytecode_hash = "none"
optimizer_runs = 1000000

# Configure remappings
remappings = [
  "@std=lib/forge-std/src/",
  "@solbase=lib/solbase/"
]

[profile.intense.fuzz]
runs = 10000